#!/bin/sh
#$Id$
TUNNEL_DOMAIN=example.com
TUNNEL_PORT=20022
TUNNEL_USER=sshtunnel
ALIVE_INTERVAL=60
PID_FILE=/var/run/auto_ssh
OPTIONS_STRING="-R 44402:localhost:22"
PAUSE=20

# Put the next line in crontab file of Your user:
# */5     *       *       *       *       /bin/sh /etc/tasks/auto_ssh
############################################################
PID_FROM_FILE=`cat ${PID_FILE}`
GO=0
echo PID скрипта $$
# Если файл есть
if [ "${PID_FROM_FILE}" != "" ]; then
    PROC_PID=`ps -aef | awk -v p=${PID_FROM_FILE}  '{if ($2==p)  print $2}'`
    echo файл ${PID_FROM_FILE}, процесс ${PROC_PID}
    if [ "${PID_FROM_FILE}" = "${PROC_PID}" ]; then
        echo уже работает программа
        GO=0
    else
	echo не работает, а пид остался
	rm ${PID_FILE}
	echo $$ > ${PID_FILE}
	GO=1
    fi
else
    echo Файла нет
    echo $$ > ${PID_FILE}
    GO=1
fi
# Запускаем?
if [ "${GO}" = "1" ]; then
    while true
    do
        echo Opening SSH session
	ssh -o ServerAliveInterval=${ALIVE_INTERVAL} -N ${OPTIONS_STRING} ${TUNNEL_USER}@${TUNNEL_DOMAIN} -p${TUNNEL_PORT}
        sleep ${PAUSE}
    done
    rm ${PID_FILE}
fi

